# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='protocolBuffer.proto',
  package='output',
  serialized_pb='\n\x14protocolBuffer.proto\x12\x06output\"F\n\x05Value\x12\x13\n\x0b\x64oubleValue\x18\x01 \x01(\x01\x12\x13\n\x0bstringValue\x18\x02 \x01(\t\x12\x13\n\x0b\x63ustomValue\x18\x03 \x01(\x0c\"J\n\x08Snapshot\x12\x11\n\ttimestamp\x18\x01 \x02(\x03\x12\r\n\x05\x61\x63tor\x18\x02 \x02(\t\x12\x1c\n\x05value\x18\x03 \x02(\x0b\x32\r.output.Value\"/\n\tTimeSerie\x12\"\n\x08snapshot\x18\x01 \x03(\x0b\x32\x10.output.Snapshot')




_VALUE = descriptor.Descriptor(
  name='Value',
  full_name='output.Value',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='doubleValue', full_name='output.Value.doubleValue', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='stringValue', full_name='output.Value.stringValue', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='customValue', full_name='output.Value.customValue', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=32,
  serialized_end=102,
)


_SNAPSHOT = descriptor.Descriptor(
  name='Snapshot',
  full_name='output.Snapshot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='timestamp', full_name='output.Snapshot.timestamp', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='actor', full_name='output.Snapshot.actor', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value', full_name='output.Snapshot.value', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=104,
  serialized_end=178,
)


_TIMESERIE = descriptor.Descriptor(
  name='TimeSerie',
  full_name='output.TimeSerie',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='snapshot', full_name='output.TimeSerie.snapshot', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=180,
  serialized_end=227,
)


_SNAPSHOT.fields_by_name['value'].message_type = _VALUE
_TIMESERIE.fields_by_name['snapshot'].message_type = _SNAPSHOT

class Value(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VALUE
  
  # @@protoc_insertion_point(class_scope:output.Value)

class Snapshot(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SNAPSHOT
  
  # @@protoc_insertion_point(class_scope:output.Snapshot)

class TimeSerie(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TIMESERIE
  
  # @@protoc_insertion_point(class_scope:output.TimeSerie)

# @@protoc_insertion_point(module_scope)
