# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='actor.proto',
  package='vazels',
  serialized_pb='\n\x0b\x61\x63tor.proto\x12\x06vazels\"F\n\x05Value\x12\x13\n\x0b\x64oubleValue\x18\x01 \x01(\x01\x12\x13\n\x0bstringValue\x18\x02 \x01(\t\x12\x13\n\x0b\x63ustomValue\x18\x03 \x01(\x0c\"9\n\x0cSessionEntry\x12\x0b\n\x03key\x18\x01 \x02(\t\x12\x1c\n\x05value\x18\x02 \x02(\x0b\x32\r.vazels.Value\":\n\x11InvocationSession\x12%\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x14.vazels.SessionEntry\"N\n\x0c\x41\x63torMessage\x12\x1a\n\x04\x63ode\x18\x01 \x02(\x0e\x32\x0c.vazels.Code\x12\x11\n\trequestId\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x02(\x0c\"N\n\rInvokeContent\x12*\n\x07session\x18\x01 \x02(\x0b\x32\x19.vazels.InvocationSession\x12\x11\n\tactorName\x18\x02 \x02(\t\"T\n\x15InvokeResponseContent\x12*\n\x07session\x18\x01 \x02(\x0b\x32\x19.vazels.InvocationSession\x12\x0f\n\x07success\x18\x02 \x02(\x08\"Q\n\x0fSnapshotContent\x12\r\n\x05title\x18\x01 \x02(\t\x12\x11\n\tactorName\x18\x02 \x02(\t\x12\x1c\n\x05value\x18\x03 \x02(\x0b\x32\r.vazels.Value\"%\n\x0fHasActorContent\x12\x12\n\nactorClass\x18\x01 \x02(\t\")\n\x17HasActorResponseContent\x12\x0e\n\x06result\x18\x01 \x02(\x08\"8\n\x0f\x41\x64\x64\x41\x63torContent\x12\x11\n\tactorName\x18\x01 \x02(\t\x12\x12\n\nactorClass\x18\x02 \x02(\t*k\n\x04\x43ode\x12\n\n\x06INVOKE\x10\x00\x12\x13\n\x0fINVOKE_RESPONSE\x10\x01\x12\x0c\n\x08SNAPSHOT\x10\x02\x12\r\n\tHAS_ACTOR\x10\x03\x12\x16\n\x12HAS_ACTOR_RESPONSE\x10\x04\x12\r\n\tADD_ACTOR\x10\x05')

_CODE = descriptor.EnumDescriptor(
  name='Code',
  full_name='vazels.Code',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='INVOKE', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='INVOKE_RESPONSE', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SNAPSHOT', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='HAS_ACTOR', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='HAS_ACTOR_RESPONSE', index=4, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ADD_ACTOR', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=683,
  serialized_end=790,
)


INVOKE = 0
INVOKE_RESPONSE = 1
SNAPSHOT = 2
HAS_ACTOR = 3
HAS_ACTOR_RESPONSE = 4
ADD_ACTOR = 5



_VALUE = descriptor.Descriptor(
  name='Value',
  full_name='vazels.Value',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='doubleValue', full_name='vazels.Value.doubleValue', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='stringValue', full_name='vazels.Value.stringValue', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='customValue', full_name='vazels.Value.customValue', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=23,
  serialized_end=93,
)


_SESSIONENTRY = descriptor.Descriptor(
  name='SessionEntry',
  full_name='vazels.SessionEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='key', full_name='vazels.SessionEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value', full_name='vazels.SessionEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=95,
  serialized_end=152,
)


_INVOCATIONSESSION = descriptor.Descriptor(
  name='InvocationSession',
  full_name='vazels.InvocationSession',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='entries', full_name='vazels.InvocationSession.entries', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=154,
  serialized_end=212,
)


_ACTORMESSAGE = descriptor.Descriptor(
  name='ActorMessage',
  full_name='vazels.ActorMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='code', full_name='vazels.ActorMessage.code', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='requestId', full_name='vazels.ActorMessage.requestId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='content', full_name='vazels.ActorMessage.content', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=214,
  serialized_end=292,
)


_INVOKECONTENT = descriptor.Descriptor(
  name='InvokeContent',
  full_name='vazels.InvokeContent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='session', full_name='vazels.InvokeContent.session', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='actorName', full_name='vazels.InvokeContent.actorName', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=294,
  serialized_end=372,
)


_INVOKERESPONSECONTENT = descriptor.Descriptor(
  name='InvokeResponseContent',
  full_name='vazels.InvokeResponseContent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='session', full_name='vazels.InvokeResponseContent.session', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='success', full_name='vazels.InvokeResponseContent.success', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=374,
  serialized_end=458,
)


_SNAPSHOTCONTENT = descriptor.Descriptor(
  name='SnapshotContent',
  full_name='vazels.SnapshotContent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='title', full_name='vazels.SnapshotContent.title', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='actorName', full_name='vazels.SnapshotContent.actorName', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value', full_name='vazels.SnapshotContent.value', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=460,
  serialized_end=541,
)


_HASACTORCONTENT = descriptor.Descriptor(
  name='HasActorContent',
  full_name='vazels.HasActorContent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='actorClass', full_name='vazels.HasActorContent.actorClass', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=543,
  serialized_end=580,
)


_HASACTORRESPONSECONTENT = descriptor.Descriptor(
  name='HasActorResponseContent',
  full_name='vazels.HasActorResponseContent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='result', full_name='vazels.HasActorResponseContent.result', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=582,
  serialized_end=623,
)


_ADDACTORCONTENT = descriptor.Descriptor(
  name='AddActorContent',
  full_name='vazels.AddActorContent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='actorName', full_name='vazels.AddActorContent.actorName', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='actorClass', full_name='vazels.AddActorContent.actorClass', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=625,
  serialized_end=681,
)


_SESSIONENTRY.fields_by_name['value'].message_type = _VALUE
_INVOCATIONSESSION.fields_by_name['entries'].message_type = _SESSIONENTRY
_ACTORMESSAGE.fields_by_name['code'].enum_type = _CODE
_INVOKECONTENT.fields_by_name['session'].message_type = _INVOCATIONSESSION
_INVOKERESPONSECONTENT.fields_by_name['session'].message_type = _INVOCATIONSESSION
_SNAPSHOTCONTENT.fields_by_name['value'].message_type = _VALUE

class Value(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VALUE
  
  # @@protoc_insertion_point(class_scope:vazels.Value)

class SessionEntry(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SESSIONENTRY
  
  # @@protoc_insertion_point(class_scope:vazels.SessionEntry)

class InvocationSession(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INVOCATIONSESSION
  
  # @@protoc_insertion_point(class_scope:vazels.InvocationSession)

class ActorMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ACTORMESSAGE
  
  # @@protoc_insertion_point(class_scope:vazels.ActorMessage)

class InvokeContent(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INVOKECONTENT
  
  # @@protoc_insertion_point(class_scope:vazels.InvokeContent)

class InvokeResponseContent(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INVOKERESPONSECONTENT
  
  # @@protoc_insertion_point(class_scope:vazels.InvokeResponseContent)

class SnapshotContent(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SNAPSHOTCONTENT
  
  # @@protoc_insertion_point(class_scope:vazels.SnapshotContent)

class HasActorContent(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HASACTORCONTENT
  
  # @@protoc_insertion_point(class_scope:vazels.HasActorContent)

class HasActorResponseContent(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HASACTORRESPONSECONTENT
  
  # @@protoc_insertion_point(class_scope:vazels.HasActorResponseContent)

class AddActorContent(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ADDACTORCONTENT
  
  # @@protoc_insertion_point(class_scope:vazels.AddActorContent)

# @@protoc_insertion_point(module_scope)
